### ISSUE TITLE
Better Room Size Changing Process

### ISSUE THREAD

**Issue by tweenko** [YoYoGames/GameMaker-Feature-Requests#1567] opened 2023-12-27 04:59 UTC
### Is your feature request related to a problem?

I usually run into a problem that i started building way too low, and there is no way of making it bigger from the top side or the left side, which is quite annoying, so I have to select all the tiles and all the objects and try to move them down for the same distance. Another issue is when I am changing the size of the room blindly, because I have no idea how much to extend my room. 

### Describe the solution you'd like

I think the BEST solution there would be is an aseprite-like canvas size tool but for rooms. 
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/139679122/aa3cb90a-5b8e-4a6b-a841-a1ac461276b3)
Would be amazing if it'd snap to a grid, too!

### Describe alternatives you've considered

Another alternative is just a dashed line showing which size the room would be when you are editing it, but this is just a lazy solution.

**Comment by nullbunny** [comment] 2023-12-27 13:21
I feel that. My current solution to that is a bit hacky but maybe it'll helps you: My template room is super big and I made an obj_room_boundaries that I can move around and resize. So far it hasn't affected my game's performance. Got the idea from Shaun Spalding's Pokeypoke livestreams.

**Comment by mistletoe** [comment] 2023-12-31 20:02
I would give up a kidney for this feature. I have to plan every Room I make around this.

**Comment by jackerley** [comment] 2024-01-03 11:30
Duplicate of #1052

**Closed by jackerley** 2024-01-03 11:30 UTC
Labels: feature request
