### ISSUE TITLE
Sprite packer optimizations

### ISSUE THREAD

**Issue by Gamer-XP** [YoYoGames/GameMaker-Feature-Requests#1320] opened 2023-09-19 04:55 UTC
### Is your feature request related to a problem?

I'm not sure how much of it can be realistically done, but can current sprite packer be optimized?
I got a single texture page with, like, 3000 images on it (4k x 2k for now). Every time I do some change in some sprite there it does a repack, which take around 30 seconds, which really makes it hard to iterate quickly.
My CPU is Intel i7-12700KF, 32Gb Ram.

### Describe the solution you'd like

Try optimize texture packer in some way. Judging by CPU load, packer uses only single core. I'm sure there are other way it can be made faster. Can also try using compute shaders.

**Comment by jackerley** [comment] 2023-09-19 08:46
Can you supply a project so that we can investigate why performance is so bad for you?

**Comment by Gamer-XP** [comment] 2023-09-19 09:27
Well, it will be a bit tough, but, like I said above, I got around 3000 small images (in ~1000 sprites, each usually around 64x64). LIkely, it's just struggling with the shear amount of images. It's not multi-threaded as well I think.
If reeeally needed - I can make a project where I copy same sprite 3000 times?

**Comment by rwkay** [comment] 2023-09-19 09:41
If you want us to improve perf on your project then share the project with us... if you want to do so privately then open a new bug and attach the project (we will close this one) - the project will be private and only we can see it.

**Comment by rwkay** [comment] 2023-09-19 09:47
just realised this is not a bug... (so we would not close it as such) - are you on LTS or the monthly? We have already speeded up monthly for projects with lots of small sprites

**Comment by Gamer-XP** [comment] 2023-09-19 09:48
I'm at 2023.1.1.62 and can't really update it for now because of event order issue

**Comment by Gamer-XP** [comment] 2023-09-19 09:56
Just tested it with the latest beta. There is no difference: It took 30:99 from Play till game starts on my verson (empty project with just sprites), and 29:51 on the Beta

**Comment by tabularelf** [comment] 2023-09-19 10:43
Make a new issue with the project, you should have an option to make it private from there.

**Comment by Gamer-XP** [comment] 2023-09-19 10:55
Nope, I don't see any options to change the visilibility for feature requests. Can send it as an old bug report, but this all sounds pretty weird.

**Comment by tabularelf** [comment] 2023-09-19 10:56
I'm talking about making a new one, not this one....

**Comment by tabularelf** [comment] 2023-09-19 10:56
Are you using the new bug reporter built into GameMaker?

**Comment by Gamer-XP** [comment] 2023-09-19 10:57
I'm also talking about making a new one - "New Issue" button. There is no visibility options.
And no, I'm not using new bug reporter since I'm using older GM version.

**Comment by tabularelf** [comment] 2023-09-19 10:58
You could boot it up into beta and do it there... Or I believe their main desk is still available for private bug reports too

**Comment by Gamer-XP** [comment] 2023-09-19 11:02
Ok, I used latest Beta to send an example project as a bug report. I linked this issues in the description.

**Comment by rwkay** [comment] 2023-09-21 19:05
see https://github.com/YoYoGames/Incoming-Bugs/issues/67 - added to next release

**Closed by rwkay** 2023-09-21 19:05 UTC
Labels: feature request

**Comment by Gamer-XP** [comment] 2023-09-22 03:48
I can't see it for some reason, even though I bound my YoYo and GitHub accounts, but thanks. I'll check it when it's released.

**Comment by Gamer-XP** [comment] 2023-10-27 15:22
Info just to confirm the change in the latest beta. Clean start time for the example project I provided.
2023.1 : 29.59s
2023.11 Beta: 10.61s

Almost 3 times faster. Great improvement!
