### ISSUE TITLE
Expose Instance Variables in Sequence Editor

### ISSUE THREAD

**Issue by ShivaSouza** [YoYoGames/GameMaker-Feature-Requests#1342] opened 2023-09-28 04:53 UTC
### Is your feature request related to a problem?

It's not.

### Describe the solution you'd like

By itself, objects and instances have exposed variables on the IDE, called "Variable Definitions".

It would be interesting if those exposed variables values could be animated in the Sequence Editor, the same way that built in variables like "x" and "y" are.
This could make dealing with more complex object animations easier.
I understand we wouldn't be able to preview the changes in the IDE, but even so this could be extremely useful.

### Describe alternatives you've considered

Since there is no way for a instance to know what is the Sequence Layer it's in, there is no real alternative for this functionality. Unless you're only using one object per Sequence

**Comment by ShivaSouza** [comment] 2023-09-28 04:55
An example would be:

You have a "hitbox object", whose damage value changes depending on what frame of the Sequence it is. And you could have multiple instances of this object in a Sequence, let's say a boss attack where multiple fire geysers erupt from the floor at different timings.

With a system like this, you could easily and fast animate these damage values.

**Comment by YYDan** [comment] 2023-10-31 10:21
Duplicate of #127 - collapsing multiple requests for this change all into the one report.

**Closed by YYDan** 2023-10-31 10:21 UTC
Labels: feature request
