### ISSUE TITLE
Allow "with" keyword to loop over arrays, ds_lists, etc

### ISSUE THREAD

**Issue by Vine2D** [YoYoGames/GameMaker-Feature-Requests#1166] opened 2023-07-02 05:15 UTC
### Is your feature request related to a problem?

`with`  is great shorthand for looping over instances with the same `object_index`, and seems implicit that it's functionality should work for user-provided lists as well. I believe it has untapped potential that could bring even cleaner code to GML and provide some nice quality of life.

### Describe the solution you'd like

An example scenario, where we want to pause many objects that do not share a parent. This is how we might currently do it:
```
with obj_player		pause = true
with obj_enemy		pause = true
with obj_bullet		pause = true
with obj_effect		pause = true
with obj_damage_number	pause = true
with obj_ui		pause = true
etc
```

And an arguably more sane solution, using the newly proposed `with` functionality:
```
var pausable =		[obj_player, obj_enemy, obj_bullet, obj_effect, obj_damage_number, obj_ui]
with pausable 		pause = true
```

---

And of course, this should work with instance IDs as well. A hypothetical scenario using the proposed functionality:
```
var characters= []
repeat(100) {
	var new_character = choose( obj_john, obj_jane, obj_dog, obj_cat )
	with instance_create_depth(random(100), random(100), 0, new_character) {
		array_push(characters, id)
	}
}

// later in some other event:
with characters {
	scream_as_loud_as_you_can()
}
```

### Describe alternatives you've considered

A highly optimistic alternative that would require all the `_list`  functions to return an array or garbage collected ds_list instead of returning `ds_list_size()`

Example use case in which this may be beneficial, this is how we currently loop over instances we're overlapping:
```
var dsl = ds_list_create()
instance_place_list(x, y, obj_thingy, dsl, false)
for (var i = 0; i < ds_list_size(dsl); i++) {
	do_thing()
}
ds_list_destroy(dsl)
```

Wherein the new `with` functionality could be as simple as
```
with instance_place_list(x, y, obj_thingy) { do_thing() }
```
The above example is my ideal goal in making this feature request, however I'd settle for less :)

**Comment by attic-stuff** [comment] 2023-07-02 15:33
this feature request is a duplicate of [this one](https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/31)—however—your first example of looping through object indices to pause 'em could, should, really be done using an array function:
```
//make a pause method
pauseall = function(value) {
	with (value) {
		paused = true;
	}
}
//when its time to pause
var duders = [ object1, object2, object420 ];
array_foreach(duders, pauseall);
```
and for your ds list example, instance place list returns a number, not a list, so i think a ds_list_foreach function would be a better feature request than allowing with to loop over lists and arrays.

**Comment by DiasFranciscoA** [comment] 2023-07-02 17:45
I've heard a lot of requesting for this but they all fall short when it comes to actual practical use. How would you handle accessing the element of the array, ds_list?

```
array = [1, 2, 3, 4];

with(array) {
   // how do you know the value?
   // this would require the creation of another built in variable - for example "value"? And the index would you be able to access the index?
}
```

What if it is an array of instance refs.

```
with(array) {
   with(value) {
      // what would "other" refer to in this case? 
   }
}
```

I don't think the way to go is using "with" on arrays or ds_lists. Since we now have a way to iterate over them (at least arrays) using the `array_foreach` we could probably reduce complexity by adding closures (but that is another request and it's already been covered)

**Comment by Alphish** [comment] 2023-07-02 22:04
@DiasFranciscoA Regarding the [1, 2, 3, 4] example - to my best knowledge, no one requested this to work. If something isn't with-able in the first place (the way instances, objects or structs are), it shouldn't be processed by the with-array construct in the first place. Both this and [my request](https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/31) relate only to use-cases where array items are valid targets for `with`. And since we only operate on with-able values, we don't need to introduce some `value` thing that would make a mess in your second example.

We don't want some unholy repurposing of "with" to simulate general-purpose "foreach", regardless of items included ([I made a separate request for more direct foreach implementation](https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/1069)). Our requests strictly relate to the context-switching behaviour `with` has always been known for, with the logical constraint of all array elements being `with`-able.

But yes, as it's been already mentioned, this feature request is a duplicate. ^^'

**Comment by jackerley** [comment] 2023-07-03 09:13
Duplicate of https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/31

**Closed by jackerley** 2023-07-03 09:13 UTC
Labels: feature request
