### ISSUE TITLE
Add ability to toggle Windowed and Borderless Windowed mode via a function.

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#895] opened 2023-06-06 15:26 UTC
*Customer's description:*

_Right now, we have to choose in the Windows Options whether the game is in Windowed Mode or Borderless Mode, and there is no way to change this setting outside of that option. If we had a function to get/set these modes, it would be a nice quality of life feature for our players._

*Customer's benefit:*

_It would give our players more flexibility in how the app is rendered, and it would cut down on the support tickets we get from players asking for this feature._

**Comment by JujuAdams** [comment] 2023-06-13 11:07
Duplicate of #984

**Comment by L-Clouds** [comment] 2023-07-05 05:23
#490?

**Comment by Alphish** [comment] 2023-09-12 14:51
@rwkay Duplicated and already implemented via `window_set_showborder`

**Comment by rwkay** [comment] 2023-09-13 09:49
duplicate issue - closing this one

**Closed by rwkay** 2023-09-13 09:49 UTC
Labels: feature request, import
