### ISSUE TITLE
Ticket: #181159 - Changing default sound file settings

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#818] opened 2023-06-06 15:22 UTC
Ticket: [Ticket #181159]

*Description:* I'd be very nice to be able to change the default settings for newly imported sounds.
I've noticed you can change the default sprite size and other settings for newly created / imported assets, and it'd be very nice to have something similar for sound files.

*Benefit:* Hi there!
I'm a game developer and sound designer, and having to manually change the bitrate and output mode (mono,stereo,3d) for every single sound I import (It's often huge amounts) is slowing down my workflow a lot.

**Comment by WangleLine** [comment] 2023-06-13 10:38
Duplicate of #460 

I'm pretty sure all of these came from a disgruntled past-me lol

**Comment by Alphish** [comment] 2023-09-12 14:41
@rwkay A duplicate.

**Comment by rwkay** [comment] 2023-09-13 09:49
duplicate issue - closing this one

**Closed by rwkay** 2023-09-13 09:49 UTC
Labels: feature request, import
