### ISSUE TITLE
Instance variables within sequences

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Feature-Requests#489] opened 2023-06-06 15:06 UTC
User request message on ticket [Ticket #190681]

 

Feature Type: feat_addition_ide
Description: You can't edit instances variables of objects created within the sequence editor.
Benefit: Using sequences to add animations to GUI elements you need to edit default variables such as the text of a button. Under the current implementation you have to hard code a button object for each variation.

**Comment by YYDan** [comment] 2023-10-31 10:20
Duplicate of #127 - collapsing multiple requests for this change all into the one report.

**Closed by YYDan** 2023-10-31 10:20 UTC
Labels: feature request, import
