### ISSUE TITLE
GameMaker 8 (or earlier) to Studio 2

### ISSUE THREAD

**Issue by hanicraft** [YoYoGames/GameMaker-Feature-Requests#1541] opened 2023-12-13 16:15 UTC
### Is your feature request related to a problem?

its very hard to convert games that i made since i was younger to studio 2, sometime recreating them is easier than converting them

### Describe the solution you'd like

add a something that converts gamemaker 8 or earlier to studio 2, it could be a tool, a button, a software, etc

### Additional context

i recently discovered my old games on my old harddrive and wanna port them to gamemaker studio 2 but as i mentioned its very hard

**Comment by stuckie** [comment] 2023-12-13 16:35
Duplicate of #1512 
As stated there, the current path is to import into GMS1, export as a GMX, then import that into current GameMaker.

**Comment by gnysek** [comment] 2023-12-13 22:33
I can confirm that I've successfully converted few GM6 and GM7 games to GMS2. It required some manual replacing for some functions (and to make it faster I've used some regex replacement in whole project outside of GM IDE), but it took me about 10 hours for game with 300+ scripts & objects.

So, generally, having GMS 1.x and GMS2/GMS2022+ is enough to achieve it.

**Comment by DragoniteSpam** [comment] 2023-12-13 22:37
I've seen more of these requests than usual popping up recently. Has the new free license brought back a lot of users who haven't been around since the pre-Studio days?

**Comment by stuckie** [comment] 2023-12-14 09:57
Closing as above..

**Closed by stuckie** 2023-12-14 09:57 UTC
Labels: feature request
