### ISSUE TITLE
Custom Parameters in Sequences

### ISSUE THREAD

**Issue by sambaylus** [YoYoGames/GameMaker-Feature-Requests#1397] opened 2023-10-19 16:40 UTC
### Is your feature request related to a problem?

In a sequence, we can keyframe parameters in a track. However, there's a need to track values beyond the provided values: Position, Scale, Index, Color...

### Describe the solution you'd like

It'd be great to be able to use Variable Definitions, or another custom defined value, as a keyframe-able parameter! We'd then be able to grab this value via code as the sequence occurs.

For example, this would be great for setting attack/knockback/stun values for hitboxes in a sequence and would create a flexible system in the IDE!

### Additional context

Here's a mockup!
![image](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/17173244/7ae6fb6f-1b01-4c85-a63f-1ad095957e4c)
"Attack" and "Stun" are parameters that can be set to different values in the sequence. They're variable definitions, but they show as custom parameters in the track!

**Comment by AtlaStar** [comment] 2023-10-21 23:04
I don't see this being possible until after the change to sequences (sequence properties) to make them easier to work with, but once that change occurs I think something like this would slot in very nicely.

**Comment by YYDan** [comment] 2023-10-31 11:24
Duplicate of https://github.com/YoYoGames/GameMaker-Feature-Requests/issues/127 - have added your mockup section into that one. Thanks.

**Closed by YYDan** 2023-10-31 11:24 UTC
Labels: feature request
